//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGOSystem
    {
        public int Id { get; set; }
        public string R_Name { get; set; }
        public string R_Address { get; set; }
        public string FoodCollectionTime { get; set; }
        public string R_Status { get; set; }
        public string E_Status { get; set; }
        public Nullable<int> A_id { get; set; }
        public Nullable<int> R_id { get; set; }
        public Nullable<int> E_id { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Restuarant Restuarant { get; set; }
    }
}
